### ISSUE TITLE
[Writing/Copy] No test for updating references within copied subtree

### ISSUE THREAD

**Issue by dantleech** [phpcr/phpcr-api-tests#142]
I may be being premature, but there doesn't seem to be a test to ensure that nodes within a subtree of a copied nodes have the references/uuids updated:

> Each REFERENCE or WEAKEREFERENCE property R in S is copied to its new location R' in S'. If R references a node M within S then the value of R' will be the identifier of M', the new copy of M, thus preserving the reference within the subgraph (see §3.8 Referenceable Nodes).

In full:

> 10.7.3 Copying to an Empty Location
> 
> When a node N is copied to a path location where no node currently exists, a new node N' is created at that location. The subgraph rooted at and including N' (call it S') is created and is identical to the subgraph rooted at and including N (call it S) with the following exceptions:
> 
> If the copy is within the same workspace, every node in S' is given a new and distinct identifier. If the copy is to another workspace, every referenceable node in S' is given a new and distinct identifier while every non-referenceable node in S' may be given a new and distinct identifier (see §3.8 Referenceable Nodes).
> 
> The repository may automatically drop any mixin node type T present on any node M in S. Dropping a mixin node type in this context means that while M remains unchanged, its copy M' will lack the mixin T and any child nodes and properties defined by T that are present on M. For example, a node M that is mix:versionable may be copied such that the resulting node M' will be a copy of N except that M' will not be mix:versionable and will not have any of the properties defined by mix:versionable. In order for a mixin node type to be dropped it must be listed by name in the jcr:mixinTypes property of M. The resulting jcr:mixinTypes property of M' will reflect any change.
> 
> If a node M in S is referenceable and its mix:referenceable mixin is not dropped on copy, then the resulting jcr:uuid property of M' will reflect the new identifier assigned to M'.
> 
> Each REFERENCE or WEAKEREFERENCE property R in S is copied to its new location R' in S'. If R references a node M within S then the value of R' will be the identifier of M', the new copy of M, thus preserving the reference within the subgraph (see §3.8 Referenceable Nodes).

**Comment by dbu** [comment]
@dantleech i think you did this. anything left to do or can we close this?

**Comment by dantleech** [comment]
Yeah, closing.
